### ISSUE TITLE
Asset Container Docs appear to be wrong?

### ISSUE THREAD

**Issue by sjclark** [statamic/migrator#112]
:joy: Spent a while trying to figure out why I was always getting Asset Container errors:
```yaml
Asset container could not be migrated: main
Assets folder cannot be found at path [image-assets].
Asset container could not be migrated: press-release-assets
Assets folder cannot be found at path [press-release-assets].
Asset container could not be migrated: theme_assets
Assets folder cannot be found at path [theme-assets].
```

Ended up having to go source diving to find the issue; which I think is related to:
https://github.com/statamic/migrator/blob/master/src/AssetContainerMigrator.php#L167:L196

It worked after I **moved all my asset containers to be WITHIN the `/site/` directory?**

Which would indicate (at least for me) that the docs are incorrect?
```
Copy your v2 project's site folder,
as well as any local asset container folders,
into the root of your v3 project.
```
```
To migrate a local asset container,
you will need to copy your assets folder into your v3 project root, 
along side your site folder.
```
OR there are potential errors calculating `base_path` somehow?

Happy to send through my project if helpful?
