### ISSUE TITLE
Collections fieldtype not renamed properly

### ISSUE THREAD

**Issue by JonKaric** [statamic/migrator#29]
When you declare collection options, it doesn't migrate `type` properly.

Behaviour when you declare options
```yaml
-
  handle: items
  field:
    type: collection
    collection:
      - articles 
      ...
```
Behaviour when you don't delare
```yaml
-
  handle: items
  field:
    type: collections
    ...
```
