### ISSUE TITLE
Blog collection errors on migrate  exception: 'Undefined index: url'

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/migrator#52]
Thought perhaps because not all posts have a `header_img` URL assigned but when I removed `header_img: ""` and re-ran the migrator, I got the same thing.

```
args:
        - 8
        - 'Undefined index: url'
        - /Users/stevengrant/Sites/digitalevangelist2020/vendor/statamic/migrator/src/ContentMigrator.php
        - 211
        -
          handle: header_img
          value: 'https://digitalevangelist-blog.s3.eu-west-2.amazonaws.com/images/vagrant_header_background-482a12a7.png'
          config:
            type: assets
            container: amazon_s3
            folder: images
            display: 'Header Image'
            max_files: 1
            width: 50
            restrict: true
          containerHandle: amazon_s3
          container:
            key: MY_AWS_KEY
            secret: MY_AWS_SECRET
            bucket: digitalevangelist-blog
            region: eu-west-2
            title: 'Amazon S3'
            driver: s3
            assets:
              images/Da12qfIXUAEXDhE.jpg:
                title: 'RSVP Live team selfie'
                alt: 'Selfie of the RSVP team at Glasgow Homeless Hackathon: Ahmed, Alan, Steven, Rebecca & Megan'

             
```
