### ISSUE TITLE
Configurator merging multiple arrays with child data incorrectly

### ISSUE THREAD

**Issue by jesseleite** [statamic/migrator#53]
User reported error on dashboard after migration (thank you @1stevengrant).  Problem is with the Configurator merging multiple arrays with child data, ie)

```yaml
widgets:
  - 
    type: form
    form: contact
    title: Recent Submissions
    fields:
      - name
      - email
  - 
    type: form
    form: subscribe
    title: Recent Subscribers
    fields:
      - name
      - email
```

Results in:

```php
'widgets' => [
    'getting_started',
    [
        'type' => 'form',
        'form' => 'contact',
        'title' => 'Recent Submissions',
        'fields' => [
            'name',
            'email',
            [
                'type' => 'form',
                'form' => 'subscribe',
                'title' => 'Recent Subscribers',
                'fields' => [
                    'name',
                    'email',
                ],
            ],
        ],
    ],
],
```
